#Development environment

server:
  port: 8082

#com.mysql.jdbc.Driver 是 mysql-connector-java 5中的，
#com.mysql.cj.jdbc.Driver 是 mysql-connector-java 6中的
#driver-class-name: com.mysql.jdbc.Driver
spring:
    datasource:
        name: mysql_test
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://192.168.43.103:3306/springboot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: root
          password: root
          initial-size: 1
          min-idle: 1
          max-active: 20
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20

mybatis:
  mapper-locations: classpath:mybatisxml/*.xml
  type-aliases-package: pers.rfeng.mybatisboot.entity


